CREATE TABLE Libro (
	LibroID INT PRIMARY KEY IDENTITY (1,1),
	Titolo VARCHAR (250) NOT NULL,
	Disponibilita BIT NOT NULL
);

CREATE TABLE Utente (
	UtenteID INT PRIMARY KEY IDENTITY (1,1),
	Nome VARCHAR (250) NOT NULL,
	Cognome VARCHAR (250) NOT NULL,
	Email VARCHAR (250) NOT NULL UNIQUE
);

CREATE TABLE Prestiti (
	PrestitoID INT PRIMARY KEY IDENTITY (1,1),
	Data_prestito DATETIME NOT NULL,
	Data_ritorno DATETIME,
	LibroID INT NOT NULL,
	UtenteID INT NOT NULL,
	FOREIGN KEY (UtenteID) REFERENCES Utente(UtenteID),
	FOREIGN KEY (LibroID) REFERENCES Libro(LibroID)
);